# Generated by Django 2.0.5 on 2018-06-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('PassWord', models.IntegerField()),
                ('Level', models.IntegerField()),
            ],
        ),
    ]
