# Generated by Django 2.0.5 on 2018-06-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Level',
        ),
        migrations.AlterField(
            model_name='user',
            name='PassWord',
            field=models.CharField(max_length=30),
        ),
    ]
